dist: trusty
language: cpp
compiler:
  - gcc-4.8
before_script:
  - sudo apt-get install  -y gcc-5.4 g++-5.4 libopencv-dev make libcurl4-openssl-dev libssl-dev
  - wget https://cmake.org/files/v3.8/cmake-3.8.1.tar.gz -O /tmp/cmake.tar.gz
  - mkdir /tmp/cmake
  - tar -xvf cmake.tar.gz -C /tmp/cmake
  - cd /tmp/cmake && \
      ./bootstrap --system-curl && \
      make -j$(nproc) && \
      make install
  - wget https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz -O /tmp/boost.tar.gz
  - mkdir /tmp/boost
  - tar -xvf boost.tar.gz -C /tmp/boost
  - cd /tmp/boost && \
      ./bootstrap.sh &&\
      ./b2 -j $(nproc) cxxflags=-fPIC threading=multi runtime-link=shared \
           --with-log --with-serialization --with-system --with-date_time \
           --with-filesystem --with-regex --with-timer --with-chrono --with-thread \
           --with-program_options \
           install
  - wget https://download.affectiva.com/linux/gcc-5.4/affdex-cpp-sdk-4.0-75-ubuntu-xenial-xerus-x86_64bit.tar.gz -O /tmp/affdex-sdk.tar.gz
  - mkdir /tmp/affdex-sdk
  - tar -xzvf /tmp/affdex-sdk.tar.gz -C /tmp/affdex-sdk
  - mkdir build
  - cd build
  - cmake -DBOOST_ROOT=/usr/ -DOpenCV_DIR=/usr/ -DAFFDEX_DIR=/tmp/affdex-sdk ..
script:
  - make
